# 测试环境配置
spring:
  # 数据库配置
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/student_management
    username: root
    password: 12345
server:
  port: 8081
# @author <a href="https://github.com/liyupi">程序员鱼皮</a>
# @from <a href="https://yupi.icu">编程导航知识星球</a>
# Redis 配置
# todo 需替换配置
redis:
  database: 1
  host: localhost
  port: 6379
  timeout: 5000
  password: 123456
# Elasticsearch 配置
# todo 需替换配置
elasticsearch:
  uris: http://localhost:9200
  username: root
  password: 123456